Adaptive step-size for ```FineRKN5```
SciML/OrdinaryDiffEq.jl pull request #1976
Opened 2023-06-19 11:40 UTC by HenryLangner

The changes enable the use of adaptive step sizes for ```FineRKN5()```. 
The already implemented convergence tests are all passed. I will add convergence tests for the damped oscillator introduced in https://github.com/SciML/OrdinaryDiffEq.jl/pull/1973, once this PR and https://github.com/SciML/OrdinaryDiffEq.jl/pull/1975 are merged. 

CC @ranocha

2023-06-19 11:46 UTC, ranocha requested changes
Could you please add some tests with adaptive time stepping, too?

2023-06-19 11:46 UTC, ranocha commented on src/perform_step/rkn_perform_step.jl
> +        end
Could you please use braodcasting here?

2023-06-19 16:18 UTC, HenryLangner commented
> Could you please add some tests with adaptive time stepping, too?

Regression tests for adaptive time stepping are added.

2023-06-20 07:03 UTC, ranocha approved these changes
Thanks!

2023-06-20 10:43 UTC, ChrisRackauckas approved these changes

2023-06-20 10:43 UTC, merged