added ROS2 method and added ROS2, ROS23 and ROS34PW methods to iipvsoop_test.jl
SciML/OrdinaryDiffEq.jl pull request #2165
Opened 2024-03-28 14:51 UTC by cwittens

## Checklist

- [x] Appropriate tests were added
- [ ] Any code changes were done in a way that does not break public API
- [ ] All documentation related to code changes were updated
- [ ] The new code follows the
  [contributor guidelines](https://github.com/SciML/.github/blob/master/CONTRIBUTING.md), in particular the [SciML Style Guide](https://github.com/SciML/SciMLStyle) and
  [COLPRAC](https://github.com/SciML/COLPRAC).
- [ ] Any new documentation only uses public API
  
## Additional context

Add any other context about the problem here.

closes https://github.com/SciML/OrdinaryDiffEq.jl/issues/2112

2024-03-28 18:28 UTC, ranocha requested changes
Thanks a lot! This looks mostly good to me. Did you test it also with some additional ODEs?

2024-03-28 18:28 UTC, ranocha commented on src/generic_rosenbrock.jl
> +    println(btilde)
```suggestion
```
Debugging leftover?

2024-03-28 18:28 UTC, ranocha commented on src/generic_rosenbrock.jl
> +2nd order stiffly accurate Rosenbrock-Wanner method with 2 internal stages with (Rinf=0).
```suggestion
    ROS2()

2nd order stiffly accurate Rosenbrock-Wanner method with 2 internal stages with (Rinf=0).
```

2024-03-29 15:55 UTC, cwittens commented on src/generic_rosenbrock.jl
> +    println(btilde)
Ups, yes

2024-03-29 15:58 UTC, cwittens commented
> Thanks a lot! This looks mostly good to me. Did you test it also with some additional ODEs?

What do you mean?

2024-03-31 12:51 UTC, ranocha commented
> > Thanks a lot! This looks mostly good to me. Did you test it also with some additional ODEs?
> 
> What do you mean?

There are some tests in the `test` folder. Did you also run the new method for additional ODEs to check that they work as expected?

Anyway, nice work :+1:

2024-03-31 12:51 UTC, ranocha approved these changes

2024-03-31 12:52 UTC, ranocha commented
Some Rosenbrock tests fail - I guess that's related to this PR?

2024-03-31 16:03 UTC, ChrisRackauckas commented
yes definitely introduced here

2024-04-21 12:17 UTC, ranocha commented
Most failing CI runs are caused by Codecov (see https://github.com/codecov/feedback/issues/301). The only exception is https://github.com/SciML/OrdinaryDiffEq.jl/actions/runs/8753631634/job/24023730348?pr=2165#step:6:956

Could you please check whether this PR causes that or whether this happens also on the current `master` branch?

2024-04-21 12:23 UTC, ChrisRackauckas commented
This PR doesn't cause that. I need to fix that one up.

But those Rosenbrock tests need to be added here.

2024-04-21 12:25 UTC, ChrisRackauckas commented
Okay yeah this looks good.

2024-04-21 12:25 UTC, merged